/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MintRouteImport } from './routes/mint'
import { Route as DexRouteImport } from './routes/dex'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimCodeRouteImport } from './routes/claim.$code'
import { Route as CardTokenIdRouteImport } from './routes/card.$tokenId'
import { Route as AgentTokenIdRouteImport } from './routes/agent.$tokenId'

const MintRoute = MintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const DexRoute = DexRouteImport.update({
  id: '/dex',
  path: '/dex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimCodeRoute = ClaimCodeRouteImport.update({
  id: '/claim/$code',
  path: '/claim/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CardTokenIdRoute = CardTokenIdRouteImport.update({
  id: '/card/$tokenId',
  path: '/card/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTokenIdRoute = AgentTokenIdRouteImport.update({
  id: '/agent/$tokenId',
  path: '/agent/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dex': typeof DexRoute
  '/mint': typeof MintRoute
  '/agent/$tokenId': typeof AgentTokenIdRoute
  '/card/$tokenId': typeof CardTokenIdRoute
  '/claim/$code': typeof ClaimCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dex': typeof DexRoute
  '/mint': typeof MintRoute
  '/agent/$tokenId': typeof AgentTokenIdRoute
  '/card/$tokenId': typeof CardTokenIdRoute
  '/claim/$code': typeof ClaimCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dex': typeof DexRoute
  '/mint': typeof MintRoute
  '/agent/$tokenId': typeof AgentTokenIdRoute
  '/card/$tokenId': typeof CardTokenIdRoute
  '/claim/$code': typeof ClaimCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dex'
    | '/mint'
    | '/agent/$tokenId'
    | '/card/$tokenId'
    | '/claim/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dex'
    | '/mint'
    | '/agent/$tokenId'
    | '/card/$tokenId'
    | '/claim/$code'
  id:
    | '__root__'
    | '/'
    | '/dex'
    | '/mint'
    | '/agent/$tokenId'
    | '/card/$tokenId'
    | '/claim/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DexRoute: typeof DexRoute
  MintRoute: typeof MintRoute
  AgentTokenIdRoute: typeof AgentTokenIdRoute
  CardTokenIdRoute: typeof CardTokenIdRoute
  ClaimCodeRoute: typeof ClaimCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex': {
      id: '/dex'
      path: '/dex'
      fullPath: '/dex'
      preLoaderRoute: typeof DexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$code': {
      id: '/claim/$code'
      path: '/claim/$code'
      fullPath: '/claim/$code'
      preLoaderRoute: typeof ClaimCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$tokenId': {
      id: '/card/$tokenId'
      path: '/card/$tokenId'
      fullPath: '/card/$tokenId'
      preLoaderRoute: typeof CardTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$tokenId': {
      id: '/agent/$tokenId'
      path: '/agent/$tokenId'
      fullPath: '/agent/$tokenId'
      preLoaderRoute: typeof AgentTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DexRoute: DexRoute,
  MintRoute: MintRoute,
  AgentTokenIdRoute: AgentTokenIdRoute,
  CardTokenIdRoute: CardTokenIdRoute,
  ClaimCodeRoute: ClaimCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
